### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Harsh-pandey9999**
Added description to how to execute programs.
added Readme file

### CODE REVIEW

**Comment by jcubic** [comment]
I would not advise using vscode live-server myself.

**Comment by Harsh-pandey9999** [comment]
It is for those who are using it for the first time and don't know how to execute programs.
Having a bit more detailed documentation won't hurt I guess.

**Comment by jcubic** [comment]
They need to know how to install NodeJS, if they know how to do this they will know how to run a program.

**Comment by jcubic** [comment]
I've added information about the live server and also how to publish the website to GitHub Pages and Netlify.

**Pull request closed without merging**
